POST http://localhost:8080/todos
Accept: application/json
Content-Type: application/json

{
  "name": "Buy a new shirt"
}
###
GET http://localhost:8080/todos
Accept: application/json
Content-Type: application/json
